### ISSUE TITLE
Push actual version to RubyGems

### ISSUE THREAD

**Issue by esaborit4code** [joshuajansen/magnific-popup-rails#9]
RubyGem's last version of this gem is `0.9.9.1` as you can check [here](https://rubygems.org/gems/magnific-popup-rails), but it doesn't match with this repo's [`version.rb` file](https://github.com/joshuajansen/magnific-popup-rails/blob/master/lib/magnific-popup-rails/version.rb).

In fact, the code I got installed through `gem install` still has the `.css.scss` extension that was removed in 0c40f291a657f0fc7e70a41cd7371fb192b14fdb.

Thanks in advance :smiley:

**Comment by tabfugnic** [comment]
:+1:

**Comment by tabfugnic** [comment]
:+1:

**Comment by joelmichael** [comment]
@joshuajansen pls do this. Your gem still has old code and gives us a deprecation warning because it hasn't been pushed to rubygems properly

**Comment by joshuajansen** [comment]
Sorry guys! It took way too long for me too respond and fix this! 

I've just updated the plugin's assets to the latest version: 1.0.0. Also built the gem and shipped version `1.0.0` to rubygems: https://rubygems.org/gems/magnific-popup-rails/versions/1.0.0
